discourse_scholar:
  discourse_scholar_enabled:
    default: false
    client: true
  discourse_scholar_api_base_url:
    default: "https://open.scholay.com"
  discourse_scholar_api_key:
    default: ""
    secret: true
  discourse_scholar_llm_endpoint:
    default: ""
  discourse_scholar_llm_api_key:
    default: ""
    secret: true
  discourse_scholar_llm_model:
    default: ""
